name: David Bedinghaus
favicon: null
layout_spectrum: 0.06018488248810172
typography_spectrum: 0.8150599345099181
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.39285994856618345
  lightness: 0.826166954357177
  saturation: 0.46938369097188115
  rhythmicContrast: 0.1308763457927853
purpose: []
